export const LOGOUT = 'LOGOUT';
export const FETCH_SEARCH_IDOL_INFO = 'FETCH_SEARCH_IDOL_INFO';
export const FETCH_IDOL_CATEGORY = 'RETCH_IDOL_CATEGORY';
export const FETCH_IDOL_CATEGORY_TOTAL_PAGE = 'FETCH_IDOL_CATEGORY_TOTAL_PAGE';
export const FETCH_IDOL_CATEGORY_JOIN_IS_FIRST = 'FETCH_IDOL_CATEGORY_JOIN_IS_FIRST';
export const FETCH_IDOL_CATEGORY_BOARD = 'FETCH_IDOL_CATEGORY_BOARD'
export const FETCH_IDOL_CATEGORY_BOARD_TOTAL_PAGE = 'FETCH_IDOL_CATEGORY_BOARD_TOTAL_PAGE'